language: php
php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm

services:
  - mysql

env:
  matrix:
    - LOWEST_DEPS=""
    - LOWEST_DEPS="--prefer-lowest"

before_script:
  - mysql -e 'create database sabredav'
  - composer self-update
  - composer update $LOWEST_DEPS

script:
  - phpunit --configuration tests/phpunit.xml
  - cp tests/composer.vobject3.json composer.json
  - composer update --no-dev
  - phpunit --configuration tests/phpunit.xml
