language: php
php:
  - 5.3
  - 5.4

services:
  - mysql

before_script:
  - mysql -e 'create database sabredav'
  - composer install
  - echo "zend.enabled_gc=0" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

script: phpunit --configuration tests/phpunit.xml
