language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1


env:
  - SABRE_MYSQLUSER="travis"
  - SABRE_MYSQLPASS=""
  - SABRE_MYSQLPASS="mysql:host=127.0.0.1;dbname=travis"
  matrix:
    - LOWEST_DEPS="" TEST_DEPS=""
    - LOWEST_DEPS="--prefer-lowest" TEST_DEPS="tests/Sabre/"

services:
  - mysql
  - postgresql


sudo: false

before_script:
  - mysql -e 'create database sabredav_test'
  - psql -c "create database sabredav_test" -U postgres
  - psql -c "create user sabredav with PASSWORD 'sabredav';GRANT ALL PRIVILEGES ON DATABASE sabredav_test TO sabredav" -U postgres
  - phpenv config-rm xdebug.ini; true
  #  - composer self-update
  - composer update --prefer-dist $LOWEST_DEPS

# Required for postgres 9.5
dist: trusty

addons:
   postgresql: "9.5"

script:
  - ./bin/phpunit --verbose --configuration tests/phpunit.xml.dist $TEST_DEPS
  - ./bin/sabre-cs-fixer fix . --dry-run --diff

cache:
  directories:
    - $HOME/.composer/cache
