language: php
php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

env:
    - VOBJECT=2
    - VOBJECT=3

services:
  - mysql

before_script:
  - mysql -e 'create database sabredav'
  - composer self-update
  - if [ "$VOBJECT" == "3" ]; then cp tests/composer.vobject3.json composer.json; fi
  - composer install --prefer-sourc
#  - echo "zend.enable_gc=0" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

script:
  - phpunit --configuration tests/phpunit.xml
